baseURL = 'http://munilab.dev/'
languageCode = 'en-us'
title = 'munilab.dev'
theme = "ananke"

[menu]

  [[menu.main]]
    name = "Start"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2

